### ISSUE TITLE
Add Path Support

### ISSUE THREAD

**Issue by jimkring** [JKISoftware/JKI-JSON-Serialization#13]
Add support for serializing and deserializing paths

**Comment by jimkring** [comment]
@tmaila I've added support for paths in a branch and I think it's ready for merge into master.

Note that I got a little creative in my round trip unit tests, since I got tired of copy+paste :-)

![2016-08-25_22-17-28](https://cloud.githubusercontent.com/assets/381432/17994898/bf0797d8-6b11-11e6-8339-8545b55e2f18.png)

**Comment by tmaila** [comment]
I think Not A Path should serialize to null and not to a string.

**Comment by jimkring** [comment]
That seems like it might make sense.

Would you do similarly for NaN?

I did some googling and it seems that JSON doesn't support NaN, +Inf, -Inf.

http://stackoverflow.com/questions/1423081/json-left-out-infinity-and-nan-json-status-in-ecmascript

**Comment by tmaila** [comment]
@jimkring you should open a separate case for NaN but no I would not do the same thing for NaN because NaN is not an object but a value and values in other languages cannot serialize to null. We could add an option to flatten NaN into null but that should not be a default behavior. The JKI JSON Serialization allows you to control if NaN/Inf are converted to symbolic values not compatible with JSON but supported by many JSON serialization libraries or flatten them to numbers. +/- Inf flattens to very large values and NaN flattens to zero. This is a weakness of JSON standard and there is not standard good workaround.
