### ISSUE TITLE
JSON library not working on LV 2012

### ISSUE THREAD

**Issue by stevem2950** [JKISoftware/JKI-JSON-Serialization#20]
Hi,

I'm having problems getting the JSON lib to work on LV 2012.  It installs fine via VIPM, but when I try to drop an icon onto a block diagram from the 'JSON Serialization' palette (or any of its sub-palettes), LV doesn't do anything (other than sound the 'error' tone).  Note that dropping icons from the other palettes in the 'JKI Tools' menu entry (i.e. 'Serialization' and 'JKI Unicode' palettes) seems to work fine.  Any idea what could be going on here?

Thanks,
Steve

**Comment by tmaila** [comment]
JKI JSON requires LabVIEW 2013 or later. This is because under the hood it uses LabVIEW JSON primitives for UTF-8 string conversions and string escaping. LabVIEW strings are not UTF-8 whereas JSON strings need to be in UTF-8. String escaping would be easy to support but to support LabVIEW 2012 or earlier we would need to find a solution for converting LabVIEW strings into UTF-8 strings. 

The package may have a bug if it installed on LabVIEW 2012, it should not install.

**Comment by stevem2950** [comment]
Hi,

It appears that the JSON stuff is only supported in LabVIEW 2013:  I tried to open a VI from this library manually, and it was compiled in LV 2013.  Is there a version of this library for LV 2012?  If not, I think that you may want to 'disallow' installation of this package in VIPM.

Regards,
Steve

**Comment by tmaila** [comment]
The package is set to require LabVIEW version 2013 or later. Which version of VIPM are you using? This seems to be a VIPM bug.

**Comment by stevem2950** [comment]
Version 2016.  I've attached 'proof' in the attached screenshots.

Thanks for the help!
Steve

![vipm_versionnumscreenshot](https://cloud.githubusercontent.com/assets/13092368/18210168/3e4e4e6c-7105-11e6-8d84-cd6e767b5fff.png)
![vimp_installscreenshot](https://cloud.githubusercontent.com/assets/13092368/18210172/441d9e88-7105-11e6-9b01-b1b0998ca77b.png)
