### ISSUE TITLE
seems to only deal with perfect set of data, and only singles set of double quotes

### ISSUE THREAD

**Issue by wegunterjr** [JKISoftware/JKI-JSON-Serialization#35]
If the data matches a json format, it should still be able to parse right?
I am having an issue where the data I am parsing looks like this when I save it to a file and the jki can't parse it:
`{""super"":""fun""}`

**Comment by francois-normandin** [comment]
I suspect you need to escape the inner quotes.

`"\"fun\""`

**Comment by wegunterjr** [comment]
Escape it before I input it into the jki json block?

**Comment by francois-normandin** [comment]
Hi Walter,
I'm sorry, I should have taken more care in answering clearly.
Your input string is not a valid JSON string. Some characters need to be escaped because they are interpreted by the serializer/deserializer as delimitation characters.

You can see a list of characters that need to be escaped [here](https://www.freeformatter.com/json-escape.html).

For example, if your input string is `"fun"`, then the flattened JSON output will be `"\"fun\""`.
The reverse unflattening operation will return `"fun"` with the quotes because the slash characters tell the algorithm to not consider the following character as a delimiter.

![image](https://user-images.githubusercontent.com/11728548/80162082-51b06e00-85a0-11ea-981b-6367f6d3b369.png)

Again, consider these two examples: 

![image](https://user-images.githubusercontent.com/11728548/80162472-735e2500-85a1-11ea-8329-c19ebab7ba14.png)

![image](https://user-images.githubusercontent.com/11728548/80162508-8c66d600-85a1-11ea-8956-28ad517260f3.png)

**Comment by JKSH** [comment]
Hi @wegunterjr, you can check if your JSON string is valid or not by using a tool like https://jsonlint.com/

According to the validator,
* `{""super"":""fun""}` is not a valid JSON string; it will not be accepted by JSON parsers.
* `{"\"super\"": "\"fun\""}` is a valid JSON string; it will be accepted by JSON parsers.
