### ISSUE TITLE
2.1 Release Tasks

### ISSUE THREAD

**Issue by jimkring** [JKISoftware/JKI-JSON-Serialization#42]
- [x] #43
- [x] #44
- [x] #45
- [x] #46
- [x] #47

**Comment by jimkring** [comment]
@nate-moehring I've create a list (above) of things to do, in order to release these new changes.  If you want to create a PR with these changes to the .vipb and prepare a new package build, that would be great!

**Comment by nate-moehring** [comment]
I'm guessing task 46 is done after the PR is merged, but I uploaded the .vip to the PR.

**Comment by nate-moehring** [comment]
Also, in the release notes I thought maybe the numbers at the end referred to PRs, but now I'm not sure.

**Comment by jimkring** [comment]
> Also, in the release notes I thought maybe the numbers at the end referred to PRs, but now I'm not sure.

Sometimes PR's don't have issue #s associated with them. I usually include (A) all issues #s that have been fixed/implemented (B) PR's that don't have issue #s

**Comment by nate-moehring** [comment]
> I usually include (A) all issues #s that have been fixed/implemented (B) PR's that don't have issue #s

Sorry, do you have direct feedback for me on the way I formatted the release notes?

**Comment by nate-moehring** [comment]
Also, I have no idea what to do with the dragon file, I haven't used Dragon.

**Comment by jimkring** [comment]
@nate-moehring would you be willing to test out the released package before we push it live on vipm.io?

https://github.com/JKISoftware/JKI-JSON-Serialization/releases/tag/v2.1.0 -> **jki_lib_json_serialization-2.1.0.44.vip**

**Comment by nate-moehring** [comment]
Thanks for putting on the finishing touches Jim!

After pulling the latest version of main and trying to run_tests.vi, I would get an inglorious LabVIEW Crash, attempting to load a VData subVI.  But it turns out I was having this problem on an older copy I had on disk, prior to your merge.  I had to update the OpenG Variant Library in order to be able to run_tests.vi successfully.

When I try to open the .vipc file, it says the configuration is empty.  I'm not sure what this VIPC file is used for.

I got this error when attempting to open the .vipb, perhaps when you built the project you targeted it for 64-bit?  I don't have 64-bit.
![image](https://github.com/user-attachments/assets/b241690f-b0f3-481d-8846-08207fd0cfb3)

Tested example VI and new functionality by replacing false with False in result JSON:
`JKI JSON Serialization.lvlib:JSON Lexer.lvclass:Run.vi:1530001<ERR>
Internal error
JSON parse error in line 1:
{"$id":"1","currentDateTime":"2024-08-18T04:27Z","utcOffset":"00:00:00","isDayLightSavingsTime":False,"dayOfTheWeek":"Sunday","timeZoneName":"UTC","currentFileTime":133684288340909801,"ordinalDate":"2024-231","serviceResponse":null}
------------------------------------------------------------------------------------------------^
in http://worldclockapi.com/api/json/utc/now


<b>Complete call chain:</b>
     JKI JSON Serialization.lvlib:JSON Lexer.lvclass:Run.vi:1530001
     JKI JSON Serialization.lvlib:JSON Lexer.lvclass:Tokenize String.vi:2030001
     JKI JSON Serialization.lvlib:Parser.lvclass:Parse Input String.vi:1590001
     JKI JSON Serialization.lvlib:JSON Parser.lvclass:Parse JSON String.vi
     JKI JSON Serialization.lvlib:JSON Deserializer.lvclass:Unflatten From String.vi:2180009
     JKI JSON Serialization.lvlib:Unflatten From JSON String.vi:4940002
     HTTP GET Current Time.lvlib:HTTP GET JSON Current Time.vi`

**Comment by nate-moehring** [comment]
![image](https://github.com/user-attachments/assets/2ae45cca-0477-4b3c-9a10-6a12bf655912)

**Comment by nate-moehring** [comment]
Relocated Example folder and reopened without having project open so that it would link to the installed package instead of the source files.  Relinked and ran as expected.

**Comment by nate-moehring** [comment]
LGTM, ship it!

**Comment by jimkring** [comment]
@nate-moehring Great! I'll release it on vipm.io now.

**Comment by jimkring** [comment]
@nate-moehring released here -> [jki_lib_json_serialization/#2.1.0.44](https://www.vipm.io/package/jki_lib_json_serialization/#2.1.0.44)

It was a pleasure reviewing your excellent submissions. These are some very nice new features that will help out a lot of folks!

**Comment by nate-moehring** [comment]
Thanks Jim.  Let me know if you have any small open source bugs or features
I can work on, I enjoyed working with you.
